# render.yaml (Blueprint) example
services:
  # Flask web service
  - type: web
    name: flask-app
    branch: main
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    # Optional persistent disk for logs/models
    disk:
      name: app-data
      mountPath: /data
      sizeGB: 1
    # envVars:
    #   - key: BOT_TOKEN
    #     sync: false           # Define in Render Dashboard (do not hardcode)
    #   - key: OPENROUTER_API_KEY
    #     sync: false

  # Telegram bot worker
  - type: worker
    name: telegram-bot
    branch: main
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py     # Or your bot script filename
    # envVars:
    #   - key: BOT_TOKEN
    #     sync: false
    #   - key: OPENROUTER_API_KEY
    #     sync: false
